import type { RentalsData } from "@/features/rentals/lib/types";

export const mockRentalsData: RentalsData = {
  renting: {
    requests: [
      {
        id: "req-1",
        listing: {
          id: "1",
          name: "Professional Chop Saw",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "John Smith",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-15",
        endDate: "2024-01-17",
        totalAmount: 187,
        status: "pending",
        createdAt: "2024-01-10",
        deliveryRequested: true,
      },
      {
        id: "req-2",
        listing: {
          id: "2",
          name: "Cordless Drill",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Sarah Johnson",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-12",
        endDate: "2024-01-14",
        totalAmount: 93,
        status: "pending",
        createdAt: "2024-01-08",
        deliveryRequested: false,
      },
    ],
    active: [
      {
        id: "rental-1",
        listing: {
          id: "3",
          name: "Angle Grinder",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Mike Davis",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-08",
        endDate: "2024-01-10",
        totalAmount: 75,
        status: "approved",
        actualStartDate: "2024-01-08",
        pickupInstructions:
          "listing is in the garage. Please text when you arrive.",
      },
      {
        id: "rental-2",
        listing: {
          id: "4",
          name: "Impact Driver",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Lisa Wilson",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-09",
        endDate: "2024-01-11",
        totalAmount: 90,
        status: "active",
        actualStartDate: "2024-01-09",
      },
    ],
    completed: [
      {
        id: "rental-3",
        listing: {
          id: "5",
          name: "Circular Saw",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Emma Brown",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-01",
        endDate: "2024-01-03",
        totalAmount: 90,
        status: "completed",
        actualStartDate: "2024-01-01",
        actualEndDate: "2024-01-03",
      },
      {
        id: "rental-4",
        listing: {
          id: "6",
          name: "Miter Saw",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Tom Wilson",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2023-12-20",
        endDate: "2023-12-22",
        totalAmount: 120,
        status: "completed",
        actualStartDate: "2023-12-20",
        actualEndDate: "2023-12-22",
      },
      {
        id: "rental-5",
        listing: {
          id: "7",
          name: "Table Saw",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Alex Johnson",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2023-12-15",
        endDate: "2023-12-17",
        totalAmount: 150,
        status: "completed",
        actualStartDate: "2023-12-15",
        actualEndDate: "2023-12-17",
      },
      {
        id: "rental-6",
        listing: {
          id: "8",
          name: "Router",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Maria Garcia",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2023-12-10",
        endDate: "2023-12-12",
        totalAmount: 80,
        status: "completed",
        actualStartDate: "2023-12-10",
        actualEndDate: "2023-12-12",
      },
      {
        id: "rental-7",
        listing: {
          id: "9",
          name: "Jigsaw",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "David Lee",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2023-12-05",
        endDate: "2023-12-07",
        totalAmount: 60,
        status: "completed",
        actualStartDate: "2023-12-05",
        actualEndDate: "2023-12-07",
      },
      {
        id: "rental-8",
        listing: {
          id: "10",
          name: "Belt Sander",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Jennifer White",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2023-11-28",
        endDate: "2023-11-30",
        totalAmount: 70,
        status: "completed",
        actualStartDate: "2023-11-28",
        actualEndDate: "2023-11-30",
      },
      {
        id: "rental-9",
        listing: {
          id: "11",
          name: "Orbital Sander",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Robert Taylor",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2023-11-20",
        endDate: "2023-11-22",
        totalAmount: 55,
        status: "completed",
        actualStartDate: "2023-11-20",
        actualEndDate: "2023-11-22",
      },
      {
        id: "rental-10",
        listing: {
          id: "12",
          name: "Reciprocating Saw",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Susan Miller",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2023-11-15",
        endDate: "2023-11-17",
        totalAmount: 65,
        status: "completed",
        actualStartDate: "2023-11-15",
        actualEndDate: "2023-11-17",
      },
    ],
    denied: [
      {
        id: "req-3",
        listing: {
          id: "13",
          name: "Pressure Washer",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        owner: {
          name: "Alex Johnson",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-05",
        endDate: "2024-01-07",
        totalAmount: 150,
        status: "denied",
        createdAt: "2024-01-02",
        deniedAt: "2024-01-03",
        denialReason:
          "listing not available for those dates due to maintenance.",
      },
    ],
  },
  lending: {
    incoming: [
      {
        id: "lend-req-1",
        listing: {
          id: "14",
          name: "Cordless drill",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        renter: {
          id: "renter-1",
          name: "Sarah Johnson",
          profileImage: "/placeholder.svg?height=40&width=40",
          rating: 4.8,
          reviewCount: 15,
          verified: true,
        },
        startDate: "2024-01-20",
        endDate: "2024-01-22",
        totalDays: 3,
        dailyRate: 21.0,
        totalAmount: 73.0,
        securityDeposit: 6.0,
        deliveryRequested: true,
        deliveryAddress: "123 Main St, Austin, TX 78701",
        deliveryFee: 10.0,
        message:
          "Hi! I need this drill for a weekend home improvement project.",
        createdAt: "2024-01-15T10:30:00Z",
        selectedWindow: "Morning (9:00 AM - 12:00 PM)",
        status: "pending",
      },
      {
        id: "lend-req-2",
        listing: {
          id: "15",
          name: "Circular Saw",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        renter: {
          id: "renter-2",
          name: "Mike Davis",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-18",
        endDate: "2024-01-20",
        totalDays: 3,
        dailyRate: 25.0,
        totalAmount: 75.0,
        securityDeposit: 15.0,
        deliveryRequested: false,
        message: "Need this for cutting deck boards.",
        createdAt: "2024-01-14T14:20:00Z",
        selectedWindow: "Afternoon (1:00 PM - 5:00 PM)",
        status: "pending",
      },
    ],
    active: [
      {
        id: "lend-active-1",
        listing: {
          id: "16",
          name: "Angle Grinder",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        renter: {
          id: "renter-3",
          name: "Lisa Wilson",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-16",
        endDate: "2024-01-18",
        totalDays: 3,
        dailyRate: 18.0,
        totalAmount: 54.0,
        securityDeposit: 10.0,
        deliveryRequested: false,
        approvedAt: "2024-01-12T09:15:00Z",
        selectedWindow: "Morning (9:00 AM - 12:00 PM)",
        status: "approved",
      },
    ],
    completed: [
      {
        id: "lend-completed-1",
        listing: {
          id: "17",
          name: "Miter Saw",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        renter: {
          id: "renter-4",
          name: "Emma Brown",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-10",
        endDate: "2024-01-12",
        totalDays: 3,
        dailyRate: 30.0,
        totalAmount: 90.0,
        securityDeposit: 20.0,
        deliveryRequested: false,
        completedAt: "2024-01-12T18:00:00Z",
        status: "completed",
      },
    ],
    denied: [
      {
        id: "lend-denied-1",
        listing: {
          id: "18",
          name: "Pressure Washer",
          imageUrl: "/placeholder.svg?height=100&width=100",
        },
        renter: {
          id: "renter-5",
          name: "Tom Brown",
          profileImage: "/placeholder.svg?height=40&width=40",
        },
        startDate: "2024-01-15",
        endDate: "2024-01-17",
        totalDays: 3,
        dailyRate: 35.0,
        totalAmount: 105.0,
        securityDeposit: 25.0,
        deliveryRequested: true,
        deniedAt: "2024-01-10T16:45:00Z",
        denialReason:
          "listing is not available for those dates due to maintenance.",
        status: "denied",
      },
    ],
  },
};
